msrv = "1.75.0"
too-many-arguments-threshold = 10
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 8
upper-case-acronyms-aggressive = false
cognitive-complexity-threshold = 30
too-many-lines-threshold = 100
avoid-breaking-exported-api = true
