// This file is automatically generated by build.rs
pub mod common {
    tonic::include_proto!("market_intel.common");
}

pub mod core_engine {
    tonic::include_proto!("market_intel.core_engine");
}
