// This file is automatically generated by build.rs
pub mod common {
    tonic::include_proto!("common");
}

pub mod core_engine {
    tonic::include_proto!("core_engine");
}

pub mod analytics {
    tonic::include_proto!("analytics");
}
